{% set name = "xopen" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 38277eb96313b2e8822e19e793791801a1f41bf13ee5b48616a97afc65e9adb3

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - pytest
    - setuptools_scm
  run:
    - python
    - python-isal  # [unix and python_impl != 'pypy']
    - isa-l  # [unix]
    - pigz

test:
  imports:
    - xopen

about:
  home: https://github.com/pycompression/xopen/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Open compressed files transparently in Python
  doc_url: https://github.com/pycompression/xopen/
  dev_url: https://github.com/pycompression/xopen/

extra:
  recipe-maintainers:
    - marcelm
    - rhpvorderman
