{% set name = "xopen" %}
{% set version = "0.8.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: dcd8f5ef5da5564f514a990573a48a0c347ee1fdbb9b6374d31592819868f7ba

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - bz2file   # [py27]
    - pip
    - python
    - pytest
    - setuptools_scm
  run:
    - bz2file   # [py27]
    - python

test:
  imports:
    - xopen

about:
  home: "https://github.com/marcelm/xopen/"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "Open compressed files transparently in Python"
  doc_url: "https://github.com/marcelm/xopen/"
  dev_url: "https://github.com/marcelm/xopen/"

extra:
  recipe-maintainers:
    - marcelm
    - rhpvorderman
