travis:
  secure:
    BINSTAR_TOKEN: dUE616FxcsPLq417qMqi3d94V8dbHrVn8ZXyWOwgn9xA1t61J4A5sP7t/isg7JPeU1d2N3fzkzoLJ2BIdcygByHxGT5zBY0AMlllii9z68j2VQrS0t+Xx07mT1IbszHR67ieR2sWZcJJE92dtPeHmUHM6sIDiCrP8HPEKOvYOyBEqSL++HcY5j+uQ1O+i2/WMcwcXY6TwJbhlO6RwHQmrplVkX6GvQ/XEi8jsjPIVWLSI/HvX4C/PEb/j9fgb1KrZb0mTIQrhFwb1Gcit2xD9ZAkq+OzocjEmVcCpBxYSg/kalMm0e5pNV/zoZoBDowXwckIRpNOvv4ha709qKTMcjv/QoUY1VaSx+rYw12VL4FzcrD5RB85WCH2fe1KP/je+aw3AOedtC6X/gyrAzAX+oUJVFzSeeqtR7TJSHl+Ze/A9l9eh/Vte92aZbb0b2FZOYp0gL7bw6RucNefY2mCNHiP3sTyaC4jbOuDPU41eJMIOQ706ym02shHRkHZ8Px2FfnDqNV/3GBe1DG1fuwI+KNjjrlqHKpl4ej/xqkBb9vMVo1IrP3JUemWSkhPUqdleaqjn15xh27H2SjpNOqow/4Xhc837JnY5s58qWAmeUX8evEvcbiQjv2czCsLU/5yRRZnAh0NaF6jQiidiEnHZprwJ3JGduJJ6EsWb1iZbY4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
